include(cppsshpackages)
include(queueptrpackages)
get_filename_component(boost_lib_dir "${HAVE_BOOST}/../lib" ABSOLUTE)
find_library(HAVE_BOOST_SYSTEM_LIB "boost_system" PATHS ${boost_lib_dir} ${boost_lib_dir}/release)
find_library(HAVE_BOOST_SYSTEM_DBG_LIB "boost_system" PATHS ${boost_lib_dir} ${boost_lib_dir}/debug)
if(HAVE_BOOST_SYSTEM_LIB)
    message(STATUS "Found boost_system library: ${HAVE_BOOST_SYSTEM_LIB}")
else()
    message(FATAL_ERROR "Could not fild boost_system library ${boost_lib_dir}")
endif()

find_library(HAVE_CPPSSH_DBG_LIB NAMES cppsshd PATHS "${CMAKE_INSTALL_PREFIX}/lib")
find_library(HAVE_CPPSSH_LIB NAMES cppssh PATHS "${CMAKE_INSTALL_PREFIX}/lib")
if ((NOT HAVE_CPPSSH_LIB) AND (NOT HAVE_CPPSSH_DBG_LIB))
    MESSAGE(FATAL_ERROR "Could not find cppssh library")
else()
    MESSAGE(STATUS "Found cppssh library ${HAVE_CPPSSH_LIB}")
endif()

find_library(HAVE_QUEUEPTR_DBG_LIB NAMES QueuePtrd PATHS "${CMAKE_INSTALL_PREFIX}/lib")
find_library(HAVE_QUEUEPTR_LIB NAMES QueuePtr PATHS "${CMAKE_INSTALL_PREFIX}/lib")
if ((NOT HAVE_QUEUEPTR_LIB) AND (NOT HAVE_QUEUEPTR_DBG_LIB))
    MESSAGE(FATAL_ERROR "Could not find QueuePtr library")
else()
    MESSAGE(STATUS "Found QueuePtr library ${HAVE_QUEUEPTR_LIB}")
endif()
